AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Globals:
  Function:
    Runtime: nodejs20.x

Resources:
  GetBoxesFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.getBoxes
      CodeUri: .
      Events:
        GetBoxesApi:
          Type: Api
          Properties:
            Path: /boxes
            Method: get

  PostBoxesFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.postBoxes
      CodeUri: .
      Events:
        PostBoxesApi:
          Type: Api
          Properties:
            Path: /boxes
            Method: post

  PostOrdersFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.postOrders
      CodeUri: .
      Events:
        PostOrdersApi:
          Type: Api
          Properties:
            Path: /orders
            Method: post

  GetOrdersFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.getOrders
      CodeUri: .
      Events:
        GetOrdersApi:
          Type: Api
          Properties:
            Path: /orders/{orderId}
            Method: get

  PostOrderItemsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.postOrderItems
      CodeUri: .
      Events:
        PostOrderItemsApi:
          Type: Api
          Properties:
            Path: /orderItems
            Method: post

  GetOrderItemsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.getOrderItems
      CodeUri: .
      Events:
        GetOrderItemsApi:
          Type: Api
          Properties:
            Path: /orderItems/{orderItemId}
            Method: get

# MyVPC:
#     Type: AWS::EC2::VPC
#     Properties:
#       CidrBlock: 10.0.0.0/16

#   MySubnet:
#     Type: AWS::EC2::Subnet
#     Properties:
#       VpcId: !Ref MyVPC
#       CidrBlock: 10.0.0.0/24

  MyElasticacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet group for ElastiCache
      SubnetIds:
        - subnet-02c217f126c0ce1d5
        
  MyElasticacheRedis:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:
      CacheNodeType: cache.t2.micro
      Engine: redis
      NumCacheNodes: 1
      Port: 6379
      VpcSecurityGroupIds:
        - !GetAtt MySecurityGroup.GroupId
      CacheSubnetGroupName: !Ref MyElasticacheSubnetGroup

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda function
      VpcId: vpc-066e6a637e37f2752
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: 0.0.0.0/0

